# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'HTSAS' do
pod "AFNetworking", "~> 2.0"
pod "XCDYouTubeKit", "~> 2.2.0"
pod "JSONJoy-Swift", "~> 0.9.1"
end

target 'HTSASTests' do

end

